### ISSUE TITLE
Application 02: Renaming Axis Titles

### ISSUE THREAD

**Issue by NickDuley** [STA518-Spring20/discussion#10]
I am working on reacreating the plot provided and I am having trouble renaming 'count' to 'Frequency' and 'attack_weak' to 'Attack Weak.' I've been trying to use the tribble() function but that lead no where.

![image](https://user-images.githubusercontent.com/44388145/81253151-ce5a3800-8ff5-11ea-8d49-f31494cdb8a0.png)

**Comment by jasonrsmith99** [comment]
You'd be better off using the _labs( )_ function instead. You can read more about it [here](https://ggplot2.tidyverse.org/reference/labs.html).
