### ISSUE TITLE
Activity 4.1

### ISSUE THREAD

**Issue by chycinsa** [STA518-Spring20/discussion#102]
When I'm trying to make my own function to scrape some TV info, the selector gadget tells me the show title CSS selector is "h1", but when I try to create  a function selecting that it tells me it isn't valid input.

**Comment by dirksem** [comment]
I had the same issue but noticed from his example it had 2 "directions" so I highlighted the entire title bar first to see ".title_block".  I also got "h1" from the title location, so when I used ".title_block h1" it worked.  I had to do the same for runtime and genre.

**Comment by dykesb** [comment]
Any idea why you need to specify "h1" *within* the ".title_block"?

**Comment by dirksem** [comment]
Is it because "h1" is an element of ".title_block", along with several other elements in ".title_block"?

**Comment by chycinsa** [comment]
That makes sense, but how did you find the title_block? I noticed there was two directions as well, but I couldn't figure out how to find the first one.

**Comment by dykesb** [comment]
I did inspect (Ctrl + Shift + I) to look at the page's HTML

Inspect panel:
![image](https://user-images.githubusercontent.com/40521287/84931807-545fa900-b0a1-11ea-9f9b-a525498b8b46.png)

Mousing over classes in the inspect window (here I moused-over the `.title_bar`):
![image](https://user-images.githubusercontent.com/40521287/84931553-efa44e80-b0a0-11ea-8910-0589b1efa801.png)

Using SelectorGadget, I selected the item I was interested in (e.g., TV Show name - `h1`), then hunted until I found the parent class (biggest box surrounding the item that I was interested in (e.g., `.title_block`):

![title_box_h1](https://user-images.githubusercontent.com/40521287/84932792-d69c9d00-b0a2-11ea-90d6-7b2e074f8510.gif)
