### ISSUE TITLE
activity0402 To Do 6

### ISSUE THREAD

**Issue by omarRmalik** [STA518-Spring20/discussion#105]
"Since we began by calculating the difference of the `max` and `min`, we could provide these as our default values.Default values get set in the function definition (i.e., `function_name <- function(x, probs = c(...)`)."

Question: max and min provide values not probabilities, the probs argument requires probabilities?

**Comment by dykesb** [comment]
Sorry for the confusion, what would be the corresponding probabilities to have the function return the difference of `max` and `min` as its default behavior?
