### ISSUE TITLE
Application 9 Error creating a choropleth map

### ISSUE THREAD

**Issue by bakjinn** [STA518-Spring20/discussion#107]
When I run my code I get the mapview but when I knit I get an error I don't understand.
<img width="371" alt="Screen Shot 2020-06-18 at 2 34 07 PM" src="https://user-images.githubusercontent.com/23545297/85059077-0c0fbc00-b171-11ea-9801-2b685ae8f9e8.png">

**Comment by dykesb** [comment]
Looks like you will need to get the developmental version of webshot: https://stackoverflow.com/questions/36043244/using-webshot-within-knitr

**Comment by bakjinn** [comment]
When I use the developmental version, phantomjs crashes when I download it automatically. I am not sure how to download from the site or if this will make a difference.

**Comment by dykesb** [comment]
I think this is going to cause issues regardless when you push to GitHub too (I believe this is an interactive visualization which won't work in GitHub) so you probably should use a different mapping toolset (e.g., see what we have used in Activity 2.3, AT 7, and the blog post in AT 9)
