### ISSUE TITLE
ggtitle glue question

### ISSUE THREAD

**Issue by omarRmalik** [STA518-Spring20/discussion#109]
How does one get the glue function to get the right number for a variable with an advancing iteration of plots? I've tried . and .x , which don't work!

**Comment by dykesb** [comment]
You could use `paste()/paste0()` with `.x` if that's more straightforward for you. To use `glue()` it depends on how your function is specified and you would use that argument in your `glue()` statement:

```
test_func <- function(arg){
glue::glue("Put this before the argument", arg," and this after the argument")
}
```

**Comment by omarRmalik** [comment]
If you gave the cylinders vector as an argument to the above test_func it will throw an error:

"All unnamed arguments must be length 1"

**Comment by omarRmalik** [comment]
This form works in the command line:

glue::glue("before", "{arg}", "after") 

however it fails to update parameters when part of ggtitle in a map.

**Comment by dykesb** [comment]
Here is a different, but similar example:

```
library(tidyverse)

dat <- tibble(
  cat = rep(seq(3, 12, by = 3), c(3,2,4,5)),
  x = rnorm(14),
  y = rexp(14)
)

vec <- sort(unique(dat$cat))

plot_fn <- function(category){
  dat %>% 
    filter(cat == category) %>% 
    ggplot() + 
    geom_point(aes(x = x, y = y)) +
    labs(title = glue::glue("This plot is for category: ", category))
  
}

output <- map(vec, plot_fn)
```

**Comment by omarRmalik** [comment]
Thank you!
