### ISSUE TITLE
activity 4.3 scrape top 100

### ISSUE THREAD

**Issue by dirksem** [STA518-Spring20/discussion#110]
When I scrape the top 100 in a for loop, I am only getting 92 observations, whether I use seq_along or 1:100.  Upon deeper digging I am missing several, including show 96 which is "Barskins".
I see the address in my imdb_tv_urls but when I try to call just 96, I get an empty tibble:

```
> scrape_show_info(imdb_tv_urls[96])
# A tibble: 0 x 3
# … with 3 variables: title <chr>, runtime <dbl>, genre <chr>
```

Then it works for any of the 92 that are populating.

```
> scrape_show_info(imdb_tv_urls[95])
# A tibble: 1 x 3
  title           runtime genre
  <chr>             <dbl> <chr>
1 True Detective       55 Crime
```

Anyone else have this issue?

**Comment by dykesb** [comment]
This is more of an issue with IMDb's web devs and not your function. For "Barkskins", they use `.titleBar , h1` while for nearly every other show they use `.title_block , h1`. You are welcome to try to make your code "complete", but I'm not too concerned with you catching everything.
