### ISSUE TITLE
Application 13 verify output

### ISSUE THREAD

**Issue by jasonrsmith99** [STA518-Spring20/discussion#112]
I'm trying to verify my output is identical to the given loop using the _all_equal_ function. When I do, I get an error that says
**"Error in if (nc != ncol(y)) { : argument is of length zero"**. Is there a better way to go about this?

![image](https://user-images.githubusercontent.com/64434718/85435670-d21a2d80-b555-11ea-8216-d997e217355f.png)

**Comment by dykesb** [comment]
I'm not too familiar with that error, and can't find any recommendations.  You can use the base R version, but it doesn't work with comparing named and unnamed vectors so you would need to do something like:

```
all.equal(output, unname(named_output))
```
