### ISSUE TITLE
Application #13: Mapping a function in purrr.

### ISSUE THREAD

**Issue by chycinsa** [STA518-Spring20/discussion#113]
```
task <- function(.x){
  return(.x[[c]] <- .x[[c]] / max(.x[[c]], na.rm = TRUE))
}
mtcars %>%
  map(task)
```

When I try to map the function, it just returns 1s. Same if I do

```
mtcars %>%
map(summary)%>%
map_dbl("Max.")
```

How can I get the proper Max?

**Comment by dykesb** [comment]
@chycinsa can you update your post to describe what you are trying/wanting to do here? These two functions look to be doing two different things.
