### ISSUE TITLE
Application 13: mtcars Max

### ISSUE THREAD

**Issue by chycinsa** [STA518-Spring20/discussion#115]
This is my code for part two on the application
`divmax <- function(x){
  return(head(x/max(x)))
}
  Max_Div <- mtcars %>% map_df(divmax)`

I cant figure out how to get it to return the car name for each row

**Comment by Rand3rino** [comment]
Check this out: https://www.quora.com/How-do-you-extract-just-the-car-name-from-mtcars-in-R
I used ```cbind()``` to join the cars to my results

Edit: This doesn't satisfy ```all_equal()``` because of the column name
