### ISSUE TITLE
App 13-all_equal with df 

### ISSUE THREAD

**Issue by monsadan** [STA518-Spring20/discussion#116]
I was trying to compare my two data frames from the problem #4 and I get an odd output. `"Different number of rows"`.

This is how I used it: `all_equal(mtcars, calc_mtcars)` and this are the two tables I'm comparing:
From the loop 
![image](https://user-images.githubusercontent.com/54322798/85476013-32749380-b585-11ea-9dce-89267fef3142.png)

From the map_df
![image](https://user-images.githubusercontent.com/54322798/85475991-225cb400-b585-11ea-8777-2cd6b70d35b7.png)

Also, how do I show the row names when using the map_df?

**Comment by Rand3rino** [comment]
Check out my response to #115 for dealing with the car names, it's not perfect but maybe it can help.

**Comment by monsadan** [comment]
I figured out what was happening, I was applying the head in the map_df pipeline and that is why the all_equal wasn't working. I removed it and the all_equal works.
