### ISSUE TITLE
#5 identical outputs

### ISSUE THREAD

**Issue by NickDuley** [STA518-Spring20/discussion#118]
I am comparing the two ouputs I have for part 5, and while from viewing the graphs by eye I can tell they are identical, the all_equal is giving me a weird error:

![image](https://user-images.githubusercontent.com/44388145/85489812-95beef80-b59e-11ea-9ead-3f83ed5da8ee.png)

Anyone have any idea what this means?

**Comment by dirksem** [comment]
I had the same issue because the output is a list.  I researched and used "all.equal.list()" instead of "all_equal" and that worked for me.  Good luck.

**Comment by NickDuley** [comment]
That worked for me as well. Thanks!
