### ISSUE TITLE
Bloxplot ISSUE

### ISSUE THREAD

**Issue by KhileahWilliams** [STA518-Spring20/discussion#12]
When typing in the code to see a boxplot display should one instantly come up or do i have to click on something else in order to see it??

**Comment by dykesb** [comment]
If you Knit your report, you should be able to see any output within the pop-up window that below the corresponding code chunk.  For example, you might have something that looks like:
```
ggplot(...) +
    code-to-create-plot
```
![recreate-application02](https://user-images.githubusercontent.com/40521287/81333489-b248ac00-9072-11ea-95ea-5cc3995e4003.png)

**Comment by KhileahWilliams** [comment]
So this is what im typing and im just very unsure of what im doing wrong. 
ggplot(iris, aes(Species, Sepal.Length)) + geom_boxplot()

**Comment by dykesb** [comment]
First, what aesthetic are you wanting to map `Species` and `Sepal.Length` to? It is best to explicitly specify these so you (and R) are certain how you want your plot to look. 

Second, where are you typing this at? Make sure it is being entered in the R code chunk.

**Comment by KhileahWilliams** [comment]
Do you mean instead of having species put Iris setosa etc?

**Comment by dykesb** [comment]
What is your x variable and what is your y variable?

**Comment by KhileahWilliams** [comment]
x is species and y is sepal.length

**Comment by KhileahWilliams** [comment]
You actually answered my question during your video.

**Comment by dykesb** [comment]
Awesome!
