### ISSUE TITLE
Activity 4.3

### ISSUE THREAD

**Issue by Hab25blu** [STA518-Spring20/discussion#121]
Scraping, having issue with scrapping getting hung up after rank 51 because the episode time isn't listed there. 

``` 
runtime<-page %>% 
    html_nodes(".subtext time") %>% html_text() %>% str_remove("\n")%>% 
     str_remove_all("\"")%>%
     str_trim("both")%>%
      print()
```

If i change the `html_nodes()` it handles things worse.
Is there a way to make it skip over those scraps or fill the field with NA? Not entirely sure how to handle this.

**Comment by dykesb** [comment]
Are you piping something into this (e.g., a webpage)? Do you get an error by running only this first show that is throwing an error (e.g., `scraping_function_name(dataset_name[51])`)? If so, what is it?

**Comment by Hab25blu** [comment]
``` 
runtime<-page %>% 
       html_nodes(".subtext time")%>% 
       html_text() %>% str_remove("\n")%>% 
       str_remove_all("\"")%>%
       str_trim("both") 
       %>% print()
  ``` 

```[1] "Drama"                 "TV Mini-Series (2020)"
[1] "Lost"
[1] "44min"
[1] "Adventure" "Drama"     "Fantasy"   ""         
[1] "Sweet Magnolias"
character(0)  #fails because of the panel it scrapes from being different, or so I believe-JEH
[1] "Drama"   "Romance" ""    
```   

_Error: Tibble columns must have compatible sizes. * Size 0: Existing data. * Size 3: Column at position 3. ℹ Only values of size one are recycled._



The issue is some of the pages for shows have the times listed in a different panel setup which breaks it. And I know when i go/ have tried to apply the other scraping things like language, country etc that it will further break this and not scrape more. Trying to figure out the better way to scrape this.

**Comment by dykesb** [comment]
I think making the values go into a dataframe column within your function should fix this.

Aside, you have a `%>%`  on the wrong line (the one before `print()`).
