### ISSUE TITLE
Application 14

### ISSUE THREAD

**Issue by omarRmalik** [STA518-Spring20/discussion#123]
Questions

1. The singer locations dataset does't have much regression material, nor is it that nestable, unless I'm missing something.

2. Does using rev code in ggmap require us to sign up for Google? Because, that requires providing credit card information. 

For 2 above the R package revgeo has a free reverse lookup!

https://towardsdatascience.com/reverse-geocoding-in-r-f7fe4b908355

It works fine for this assignment!

**Comment by dykesb** [comment]
For 1, I see `duration`, `artist_hotness`, and `artist_familiarity` as three potential variables. You could build a model for each country/state/city/etc., year, artist... 

For 2, I will be updating this AT with the [**revgeo**](https://github.com/mhudecheck/revgeo) package for later semesters. Use this instead of  `ggmap::revgeocode`.

**Comment by omarRmalik** [comment]
Thank you!

best,

Omar

**Comment by omarRmalik** [comment]
R studio cloud crashes with the number of Photon API calls this assignment requires! Its a computationally expensive process, very slow.

**Comment by dykesb** [comment]
Good to know.

I will be talking more about this before the end of the course, but the free version of RStudio Cloud is not the optimum set-up for all analyses (but is for minimizing the initial cognitive load that goes with installing any new software on computers). If anyone chooses to do the items that require using **revgeo**, I will strongly encourage you to [install R/RStudio](https://happygitwithr.com/install-r-rstudio.html) on your machine. Also, you can [install](https://happygitwithr.com/install-git.html) and [introduce](https://happygitwithr.com/hello-git.html) yourself to Git on your machine.

**Comment by jasonrsmith99** [comment]
I found that it take around 30 minutes for R to go through all the coordinates. Is there a way to save the results so  it doesn't take that long when we knit the document? I've tried setting 'cache = TRUE' in the chunk options but that doesn't appear to have done anything.

**Comment by omarRmalik** [comment]
You can use saveRDS to save an rds file. This can then be read into your R session.

**Comment by jasonrsmith99** [comment]
That's a good trick! I'll have to remember that for next time.
