### ISSUE TITLE
Activity 4.4

### ISSUE THREAD

**Issue by KhileahWilliams** [STA518-Spring20/discussion#124]
![Screen Shot 2020-06-26 at 11 11 45 AM](https://user-images.githubusercontent.com/64782486/85872579-f2d4c400-b79d-11ea-9ae7-6a0284b7e024.png)

Could i get some help on how to solve this error.

**Comment by dykesb** [comment]
See #119

**Comment by KhileahWilliams** [comment]
i updated it now it says could not find function "rowwise"

**Comment by dykesb** [comment]
Try restarting your session (in the drop-down menus: Session > Restart R). Be sure to load everything back in.

**Comment by KhileahWilliams** [comment]
that helped. thanks
