### ISSUE TITLE
Application Task 14 singer/gender wage gap data

### ISSUE THREAD

**Issue by schmimol** [STA518-Spring20/discussion#125]
I’ve been working on application task 14 for what feels like a while and I’m not really getting anywhere. I just don’t understand how to get the singer data for parts 3.1/3.2 and then the gender wage gap data in 3.4. Any help would be great.

**Comment by dykesb** [comment]
For 3.1/3.2, after you install and load the package, you can install the three separate datasets by doing:

```
data("name")
```

Where `name` is either `locations`, `singer_locations`, `songs` (in [Joey's example](https://github.com/JoeyBernhardt/singer/#example), they use `"songs"`).

For 3.4, Activity 4.1 would be a place to start and notice that the data is already available in a table (vs what you had to do in the second half of Activity 4.1 and Activity 4.3 where you needed to visit individual pages to scrape the data).

**Comment by schmimol** [comment]
I was able to get the data. But for 3.4, I think the saving your code in an R script called `paygap.R` is what's confusing me.

**Comment by dykesb** [comment]
R4DS [Chapter 6](https://r4ds.had.co.nz/workflow-scripts.html)
