### ISSUE TITLE
activity0404 to do #5

### ISSUE THREAD

**Issue by dirksem** [STA518-Spring20/discussion#126]
When running broom::tidy(model), broom::glance(model), and broom::augment(model) in the mutate to create 3 columns after creating the "model" column, I am getting errors.  Any ideas?  Probably missing something simple, as I find myself struggling with this material. Thanks!

**Comment by dykesb** [comment]
What errors are/were you getting? How did you resolve this?

**Comment by dirksem** [comment]
First, I asked my team members, then I posted this, and after a few minutes my team mate figured out I wasn't mapping through the data for the three columns.  It made total sense that I had to call the functions for the second argument of map to create each column; this should have jumped out at me from mapping to get the "model" column.  Missing the obvious sometimes...definitely not feeling confident in iterating yet.

**Comment by dykesb** [comment]
It took me a while to get used to the `map_*()` functions and even now I sometimes have to search for the specific one that I want to use.

Some words to live by:

<blockquote class="twitter-tweet"><p lang="en" dir="ltr">you 👏🏼 don&#39;t 👏🏼 have to 👏🏼👏🏼 know 👏🏼 EVERYTHING 👏🏼👏🏼👏🏼 by heart 👏🏼 to be a good 👏🏼👏🏼👏🏼 PROGRAMMER👏🏼 <a href="https://t.co/VYjvvSVbYV">https://t.co/VYjvvSVbYV</a></p>&mdash; Chelsea Parlett-Pelleriti (@ChelseaParlett) <a href="https://twitter.com/ChelseaParlett/status/1275563955499397121?ref_src=twsrc%5Etfw">June 23, 2020</a></blockquote>
