### ISSUE TITLE
Activity 4.5 To-Do 4: Plotting listed values

### ISSUE THREAD

**Issue by NickDuley** [STA518-Spring20/discussion#130]
In To-Do 4, I generated the 1000 means, but I am having a hard time plotting the density plot for them. Is it just as simple as doing ggplot() with geom_density and I am coding it incorrectly, or is there something else to it that I am just missing?

**Comment by dykesb** [comment]
Right before `Chunk 2: norm-samp` I say:

> Below I have generated 1,000 samples from a Normally distributed variable with a mean 50 and standard deviation 10 (remember to remove the `eval = FALSE`) and constructed a *density plot*.

Then create 1,000 samples and a *density plot*.

**Comment by NickDuley** [comment]
I am still confused because when I use the replicate() function, I get a large list with a 1000 elements. Is this is not what I should have?

![image](https://user-images.githubusercontent.com/44388145/86175309-15921000-baf1-11ea-90e0-2fa6478926db.png)

![image](https://user-images.githubusercontent.com/44388145/86175320-1c208780-baf1-11ea-9ee4-9b757aa8027e.png)

**Comment by dykesb** [comment]
You have 1,000 replications of 1,000 `exponential(0.02)` samples. You need to plot the means so how can you generate the mean of each of these 1,000 replications?

**Update**: I notice you call this `gen_exp_samp_30`. Were you intending to have 1,000 replications of 30 `exponential(0.02)` samples?

**Comment by NickDuley** [comment]
Yes I was. I since fixed that error of having 30 samples vs. 1000, and I have a line of code that creates the mean, but I can't figure out how to save it to itself to create the density plot

![image](https://user-images.githubusercontent.com/44388145/86177524-ce0d8300-baf4-11ea-8e8b-5defefb0d74e.png)

**Comment by dykesb** [comment]
Why would you assign it to itself? It is a different object so create a new object - these are means, not samples of 30.

**Comment by NickDuley** [comment]
Should the new object being created be just a set list of values vs a data table? When saving the means, I get a list of values

![image](https://user-images.githubusercontent.com/44388145/86179192-d0bda780-baf7-11ea-951f-5b6cb8da658f.png)

**Comment by dykesb** [comment]
It looks to be a numeric vector with thirty values. 

Recall that `map_dbl()` outputs an atomic vector: https://purrr.tidyverse.org/reference/map.html
This was also covered in Chapter 20 ([Vectors](https://r4ds.had.co.nz/vectors.html)) of the text and the corresponding RStudio Primers.
