### ISSUE TITLE
RStudio Crashes

### ISSUE THREAD

**Issue by fracassc** [STA518-Spring20/discussion#132]
I've been receiving a pretty constant RStudio crash while working on Activity 4.6 when doing the 1,000 bootstrap samples.

```
The Previous R session was abnormally terminated due to an unexpected crash.
You may have lost workspace data as a result of this crash.
```

 Has anyone else been receiving similar issues? Not sure if it's my session itself, or if there if I'm hitting resource issues in these functions. Even the example bootstrap samples and means will give this error when I try and run it.

After this error it will restart RStudio, and then it appears to be frozen, I'll manually restart the session and the same error will occur when I run the bootstrap code. All the previous code seems to run fine.

**Comment by fracassc** [comment]
(Marvin explained this to me) 

This code will quickly take up the memory capacity for a session, I had to clear out my workspace to get stuff to run again. Even then though I'm fighting with the capacity to run all that is required.

**Comment by dykesb** [comment]
See if reducing the number of bootstrap samples you do (say, only 100) avoids this issue.
