### ISSUE TITLE
App Task 7: Updating your Map

### ISSUE THREAD

**Issue by bakjinn** [STA518-Spring20/discussion#137]
I am trying to set fill in the geom_polygon layer but division is not being recognize and I'm not sure why.

<img width="454" alt="Screen Shot 2020-07-09 at 6 22 19 PM" src="https://user-images.githubusercontent.com/23545297/87096717-6ef4f000-c211-11ea-8265-6c77a1f0d9bd.png">

**Comment by dykesb** [comment]
`division` doesn't currently exist in `us`, but you could always join it similarly to how you brought it into `dennys_laquinta`.

**Comment by bakjinn** [comment]
<img width="453" alt="Screen Shot 2020-07-09 at 6 46 22 PM" src="https://user-images.githubusercontent.com/23545297/87098078-84b7e480-c214-11ea-9649-1e4539334bdc.png">
Do I have to convert the us states into abbreviations in order to join it with the dennys_laquinta dataset?

**Comment by dykesb** [comment]
If you want to go that route, `state.name` can be added to your `state_division` tibble above.

**Comment by bakjinn** [comment]
When I add the 'state.name' to state_division doesn't it get removed when I do the left join to the 'dennys_laquinta' dataset?
<img width="446" alt="Screen Shot 2020-07-10 at 11 52 47 AM" src="https://user-images.githubusercontent.com/23545297/87173545-f12df480-c2a3-11ea-8d5c-4afbd325338b.png">

**Comment by dykesb** [comment]
`left_join()` adds all columns from the right-hand-side that aren't in the left-hand-side when joining on specific columns.
