### ISSUE TITLE
Team Project

### ISSUE THREAD

**Issue by chycinsa** [STA518-Spring20/discussion#138]
Can you provide advice to help make sure we know we have done is sufficient? I am particularly worried about this project because of how open ended it is.

**Comment by dykesb** [comment]
You and each of your team members have two examples (both midterm projects) of what I think are satisfactory projects – granted, these are more directed. Each group of students has their own project that they are working on and I’ve given recommendations/suggestions/feedback on your proposals. Some questions to guide you are:

- Do you answer the research questions that you sought to look into? 
- Do you effectively use the tools that we have covered in class to answer these questions?
- Could your code be made more efficient?
- Do you use a combination of graphical and tabular summaries to provide insight into your questions?
- Are you accepting most of the default behaviors of the functions you use or are you being creative and extending the tools?
- Do you clearly articulate what you are doing and why that is a correct way to do it?
- Do you have a report and a data product (poster, slides, shiny app, etc.)

**Comment by chycinsa** [comment]
Does the data product (ie. Poster) have to be made in R or can we use our findings in a Word document or PowerPoint Presentation?

**Comment by dykesb** [comment]
Higher marks will be reserved for effective implementation in R. You've been creating text documents throughout this course (i.e., Rmd file) and have been pointed towards packages that can create slide presentations and posters (e.g., {pagedown} and {posterdown} from Application Task 15). If you want to make slides, the {[xaringan](https://github.com/yihui/xaringan)} package is another widely used alternative to {pagedown}.
