### ISSUE TITLE
Syllabus questions & one GitHub/RStudio Cloud question

### ISSUE THREAD

**Issue by joblara8** [STA518-Spring20/discussion#14]
I understand if we don't end up having time for these questions, but here they are:
1) Could you elaborate on what the projects (both the individual and team ones) will be like?
Will they be quite similar to the Application tasks but bigger?
2) Will each Activity & Application task be prefaced by a primer that gives a good summary of the relevant chapters in the book?
3) What is the difference between pushing and pulling with regard to project we are working on in RStudio Cloud? Do we ever do both at the same time, or no?

**Comment by dykesb** [comment]
I think I covered these during the session, but please re-open it if you do not feel like I did.
