### ISSUE TITLE
Team Project: College Locations

### ISSUE THREAD

**Issue by NickDuley** [STA518-Spring20/discussion#140]
I need to find a dataset of all the coordinates of every university and college. Anyone have websites/resources that I could look into to find this?

**Comment by dykesb** [comment]
You might be able to scrape them from: https://en.m.wikipedia.org/wiki/Lists_of_American_universities_and_colleges

It will probably take a lot of thought because pages do not appear to be consistent.

Or there might be an easier way to pull from IPEDS: https://nces.ed.gov/ipeds/CollegeMap/

**Comment by NickDuley** [comment]
I found a website that helped me find a different task I had (One point per state) but it asks for a list of items to find from a csv file

https://geocode.localfocus.nl/
