### ISSUE TITLE
Data-product

### ISSUE THREAD

**Issue by Rand3rino** [STA518-Spring20/discussion#141]
Hi professor,

Can you clarify what goes into ```/data-product```? Is this only the poster/shiny app or does this include the ```.Rmd```, the data, and the github markdown file too?

**Comment by dykesb** [comment]
Only the materials used to create your data product should be in your `/data-product` folder. For example, if you created a Shiny App, you would call `runApp(data-product)`; if you created slides or a poster, the corresponding `.Rmd` files and figures would be contained within `/data-product`. All the materials for you report should be in the main-level of your repository.
