### ISSUE TITLE
application02- Pokemon Chart dodge issue

### ISSUE THREAD

**Issue by bakjinn** [STA518-Spring20/discussion#16]
I am having trouble with unstacking my bar chart. When I add position="dodge" my chart will not adjust correctly.

**Comment by dykesb** [comment]
> I am having trouble with unstacking my bar chart. When I add position="dodge" my chart will not adjust correctly.

I edited out the link to a private repository that others won't have access to.

See if the information at **ggplot2**'s [`position_dodge`](https://ggplot2.tidyverse.org/reference/position_dodge.html) page helps (remember the examples at the bottom).
