### ISSUE TITLE
alpha and size

### ISSUE THREAD

**Issue by LauraRK** [STA518-Spring20/discussion#17]
Hi All,
I am having trouble changing alpha and size when my graph has a color feature. 

```
p <- ggplot(iris, aes(x=Sepal.Length, y=Sepal.Width))
p + geom_point(mapping=aes(color= Species, alpha=.01, size=.1))
```

if I change size does not change size and I get alpha and size in my legend which is not what I want.
I also tried a few different orderings and looking at the book. 
for example I tried

```
p + geom_point(mapping=aes(color= Species))+geom_point(alpha=.01)
p + geom_point(mapping=aes(color= Species))+geom_point(mapping=aes(alpha=.0001))
```

I am probably misunderstanding something here about the syntax for ggplot so if you know how this is applied and can help me out that would be great.
Thanks Laura

**Comment by dykesb** [comment]
This is an issue with **mapping** vs. **setting**. With mapping, you want to assign a variable to a visual feature (e.g., size, alpha, x-axis, y-axis, or color). With setting, you want to assign a fixed value to a visual feature. Mappings are arguments *within* the `aes()` portion. Settings are arguments within the `geom_...()`, but *outside* of the `aes()` portion.

For example:

```
p + geom_point(mapping = aes(color = Species), alpha = .01)
```

On a side note, each time you add (`+`) a layer to a plot, it creates a separate layer in your visualization that inherits the global mappings (from the `ggplot(<data>, mappings = aes(...))`  portion). So when adding two `geom_point(...)` layers, their mappings/settings do **not** communicate with each other. We will cover this more ~3 weeks when we return to plots after we work with wrangling data!

**Comment by LauraRK** [comment]
thank you that really helps.
