### ISSUE TITLE
Team Activity 1.2 Final Push

### ISSUE THREAD

**Issue by chycinsa** [STA518-Spring20/discussion#18]
I'm confused on the final Push. Do we just do the same as we did on the first push or something else?

**Comment by dykesb** [comment]
Prior to completing the Pull Request, you have a number of different versions of the `activity0102-visualization-basics.Rmd` file. These being the, 

- `master` branch version (this should not have any new details added to it),
- `<your-username>` branch version (this is your copy with your responses),
- `<team-member-username-1>` branch version (one of your Team Member's copy with their responese),
- ... (depending on how many Team Members you have), and 
- `<team-member-username-n>` branch version (your last Team Member's copy with their responese).

Your entire Team has the ability to serve as the owner of your GitHub repository to merge these versions together to the `master` branch, but I want you to help each other out and talk through what parts of each Team Members copy you like. This can become rather confusing if you each try to merge your content separately. Therefore, you should watch and help one of your Team Members as they handle merging conflicts from all of the Pull Requests. 

Alternatively, you could have each Team Member take turns submit a pull request from their branch to the `master` branch, fix any merge conflicts **as a Team**, then move on to the next pull request.

You will do this in your Activity 1.2 GitHub repository once each Team Member's individual branch in complete and pushed there.
