### ISSUE TITLE
Can't link RStudio Cloud with Github account

### ISSUE THREAD

**Issue by jasonrsmith99** [STA518-Spring20/discussion#2]
When I click on the 'sign up with Github' button and put in my login information, I get the following error message
![image](https://user-images.githubusercontent.com/64434718/81023248-c9528880-8e3d-11ea-9147-948639e576c0.png)

I looks like I've created an RStudio Cloud account linked to my gmail at some point in the past. Is not having the account linked directly to my Github going to be a problem? If so is there a way to delete my current cloud account?

**Comment by dykesb** [comment]
It's not going to be an issue. I direct you all to signup with your GitHub account so that you do not not become too overwhelmed with needing to remember several logins.

**Comment by jasonrsmith99** [comment]
Quick side note: if you're in a similar situation, you'll be asked to sign into Github when you create a new project from a repo. **You cannot have multifactor authentication enabled on your Github account**. If you do, it won't accept your login info.
