### ISSUE TITLE
Application 2-Step 6

### ISSUE THREAD

**Issue by Hab25blu** [STA518-Spring20/discussion#20]
Hey, I have a question regarding **step 6**. I am not sure I understand the directions.

Snipe Picture #Snipe picture didn't upload-added step below

_Step 6: Dress up your Report Using your Markdown skills, add at least two relavent images from the web. Make it so you do not need to upload the actual image to your repo. Once you have completed this task knit, commit, and push your report one last time. Verify that the image(s) that you added are being displayed appropriately._

Is it using the markdown to put the images in R so that they show up in the knit report and md file?

**This format?**

![Picture](Web image link)

What kind of images are acceptable? May pokemon images be used? Or is this more academic such another bar or pie chart from somewhere?

**Comment by dykesb** [comment]
The `![Picture Description](link-to-image)` works for both images you find from the internet and images you upload to your folders (e.g., when we create plots with **ggplot2**, it creates an image folder that stores the actual `.png` files created).  I do not want you to download files from the internet then call them locally - these should all be web images. These should be images that "add flavor" to your report in that it thematically fits (Pokémon images would be an appropriate thematic choice).

When you knit and also when you commit/push, you should verify that the images are appearing as you intended.
