### ISSUE TITLE
activity0103-can't knit/no devtools

### ISSUE THREAD

**Issue by dirksem** [STA518-Spring20/discussion#21]
I am having the same problem with knitting for activity 0103 that I had in activity 0102, getting the error for no emo.  I used Jason's instructions for activity 0102 and it worked fine, but I am not getting the same results with activity 0103.  Devtools loads but then the second command 

devtools::install_github('hadley/emo')

will not execute and I am getting an error.

> devtools::install_github('hadley/emo')
Error: Failed to install 'unknown package' from GitHub:
  HTTP error 403.
  API rate limit exceeded for 34.203.76.245. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)

  Rate limit remaining: 0/60
  Rate limit reset at: 2020-05-11 19:23:05 UTC

  To increase your GitHub API rate limit
  - Use `usethis::browse_github_pat()` to create a Personal Access Token.
  - Use `usethis::edit_r_environ()` and add the token as `GITHUB_PAT`.

Anyone know what I am doing wrong or missing?  Thanks for any help!

**Comment by dykesb** [comment]
What is the name of the RStudio Project that you are working in?

I actually only see you with one Project in our workspace. Make sure you are creating projects in our `Spring20_STA518_S01` workspace as I have a lot of these packages pre-installed.

**Comment by dirksem** [comment]
That was my problem, I was in my personal workspace instead of our session workplace.  Having trouble getting used to Github/R Studio.  Thank you!

**Comment by dykesb** [comment]
I apologize for the seemingly disjoint tools that we are using. I will do my best to be consistent in my directions to attempt to mitigate this confusion, but I am always happy to help!
