### ISSUE TITLE
activity 0103 (TODO-5)

### ISSUE THREAD

**Issue by KhileahWilliams** [STA518-Spring20/discussion#22]
when doing todo 5 I keep getting an error message that pops up saying "could not find function arrange" 
how do I fix it to not get that message?

**Comment by KhileahWilliams** [comment]
![Screen Shot 2020-05-12 at 9 53 56 AM](https://user-images.githubusercontent.com/64782486/81700386-952b2900-9436-11ea-8083-98eb89949608.png)

**Comment by dykesb** [comment]
It looks like you didn't have the `tidyverse` loaded (i.e., `library(tidyverse)`) . I say this because the Error says `could not find function %>%`. Is this how you resolved this?

**Comment by KhileahWilliams** [comment]
Yes I added in tidyverse, I think I may have accidentally deleted it.
