### ISSUE TITLE
Activity 0102 Merging Conflicts

### ISSUE THREAD

**Issue by Rand3rino** [STA518-Spring20/discussion#24]
My team is having problems merging where the resolve conflict isn't available in the online editor because the conflicts are too complex. Our branches have the .png files which probably are the cause. Were we not supposed to push the images to our branches?

**Comment by omarRmalik** [comment]
Yes you should only push the R markdown file.

**Comment by omarRmalik** [comment]
It helps a lot if you have google teams session where you resolve these. Talking through them is much easier than looking at the code.

**Comment by millerp217** [comment]
We were on a live google meet and these pushes happened before the workflow
was modified to only include the rmd.  Is the solution to push another
commit without the png files just to get this completed?

After the call, I tried forcing the merge via the got desktop app but
wasn’t able to make that work either. I’m pretty sure I was doing something
wrong at that point because it was late.

**Comment by dykesb** [comment]
You could remove the `png` files from your individual branch (either on GitHub or in the **Terminal** if your feel comfortable with that) if you accidentally pushed them.

**Comment by dykesb** [comment]
If you weren't able to get this resolved, I would be happy to sit in on your next attempt. It might give me a better sense of how my current directions work in practice and see if I need to update them at all.

**Comment by millerp217** [comment]
I did try this again last night and when I knitted the file again in R,
committed it, and pushed it the .rmd to Git there was no option to leave
out any of the .png files.

Once in Git the pull request to merge my branch to the master produced the
same “too complex” error.  However, I was able to create a pull request to
a teammates branch and Git would allow that. Should we proceed with that
route?

I’m happy to stay on after the lecture and step through it.

**Comment by dykesb** [comment]
I'll stick around afterwards.

**Comment by Rand3rino** [comment]
After deleting the folder with the images, I still had the "too complex" error. 

I was able to get around all of this by creating a new branch off of master and naming it Rand3rino-v2. I pasted in my .Rmd file, knit the report, and committed just the .Rmd.
