### ISSUE TITLE
Can't login to Rstudio through Github account

### ISSUE THREAD

**Issue by dadrian14** [STA518-Spring20/discussion#25]
I'm having trouble doing the "Login with Github" on RStudio at the beginning of Assignment 01.  I keep getting this error.

![image](https://user-images.githubusercontent.com/50752398/81862033-18cc3f00-9537-11ea-9a8a-8dc75af16a52.png)

Any thoughts?

**Comment by dykesb** [comment]
You probably signed up for RStudio Cloud using `adriand1@gvsu.edu` at some other point. You will need to sign in with your email and password (you might need to request a change in password if you've forgotten it) and you won't experience any issues by going that route. I recommend the "Login with Github" to avoid the number of new accounts that learners are creating.

**Comment by dadrian14** [comment]
Gotcha.  I'm good to go now.  I did Application 01 - very nice!
