### ISSUE TITLE
Can't get proper maximum for To Do #4 in Activity 0104

### ISSUE THREAD

**Issue by dirksem** [STA518-Spring20/discussion#26]
I can't seem to get the maximum to display for the variable "median" with my code and I'm not sure why.  It is displaying the median for the maximum, yet the minimum seems to work just fine.  I'm sure I'm missing something simple, can anyone help?

```{r summary-earnings}
college_recent_grads %>% 
  summarise(sample_size = n(), mean = mean(median), standard_deviation = sd(median), minimum = min(median), median = median(median), maximum = max(median))
```

sample_size<int> | mean<dbl> | standard_deviation<dbl> | minimum<dbl> | median<dbl> | maximum<dbl>
-- | -- | -- | -- | -- | --
173 | 40151.45 | 11470.18 | 22000 | 36000 | 36000

**Comment by dirksem** [comment]
By moving maximum before median, it solved the problem.  Not sure why.  Thanks to Chris Fracassi for the solution!

**Comment by jasonrsmith99** [comment]
I made the same mistake. The code
```r
median = median(median)
```
is redefining the variable _median_ as 36000.

so when you try to take the maximum, you're really asking for the maximum of 36000. not the medians in the dataset.

In the _summarize( )_ function, I renamed _median_ to something shorter to avoid the problem.

**Comment by dirksem** [comment]
Thanks Jason, now it makes sense of what is happening in the code.  I knew I was missing something!

**Comment by dykesb** [comment]
Closing this as I believe @jasonrsmith99 answered it.

In my own workflow, I like to name summarized variables as a combination of the statistic that I am calculating and the variable name (e.g., `med_med_earn = median(median)` - this dataset has some unfortunate variable names, but something you will very likely run into in practice).
