### ISSUE TITLE
activity0104 major category summary statistics

### ISSUE THREAD

**Issue by chycinsa** [STA518-Spring20/discussion#27]
For the assignment, when you want summaries for the major categories, do you mean every major category or just the 4 stem ones?

**Comment by dykesb** [comment]
Can you provide some more details as to what section/item you are working on (so that others have some more background)? I think you are asking in general from To-Do 5 and beyond (?). For these, I just want them for `major_category`, not the `stem_category` vector that was created in Activity 1.3.

**Comment by chycinsa** [comment]
To do 5 where you ask for information about the center, shape, etc of the categories.

**Comment by dykesb** [comment]
I removed the `#` before 5 in your comment so people didn't get confused when they went to that unrelated linked community/Issue.

Did my response above answer your question?
