### ISSUE TITLE
Pokemon height change clarification

### ISSUE THREAD

**Issue by jasonrsmith99** [STA518-Spring20/discussion#28]
I'm a bit confused on what we're supposed to calculate for the _percent-height-change_ chunk. The directions sound like we're supposed to calculate the percentage of pokemon that grew during evolution, but all the pokemon grew. This makes me think we're supposed to calculate the percent change in height.

**Comment by dykesb** [comment]
Sometimes insight isn't groundbreaking.  I want percent that grew, not the percent change in height.
