### ISSUE TITLE
Challenge Question from May 14 Session

### ISSUE THREAD

**Issue by dykesb** [STA518-Spring20/discussion#30]
We created a table showing the five countries that had the sharpest 5-year drop in `lifeExp` (copied below). What explains each of these drops? You will not find these from the dataset, and will need to do some research for the story behind these values.

```
## # A tibble: 5 x 4
##   country   continent  year change_life_exp
##   <fct>     <fct>     <int>           <dbl>
## 1 Cambodia  Asia       1982           19.7 
## 2 China     Asia       1967           13.9 
## 3 Rwanda    Africa     1997           12.5 
## 4 Rwanda    Africa     2002            7.33
## 5 Mauritius Africa     1957            7.10
```

**Comment by ormalik** [comment]
The drop in China coincides with the Great Cultural Revolution. Cambodia and Rwanda were both facing civil war.

**Comment by millerp217** [comment]
Looks like 1957 is when Mauritius went to "internal self-government" while still a colony of the UK.

**Comment by Hab25blu** [comment]
Rwanda was indeed in a civil war, and there was a mass genocide.

**Comment by jasonrsmith99** [comment]
The large strides Rwanda has taken in terms of healthcare after the 1994 genocide is a contributing factor to the large increases in life expectancy in 1997 and 2002. However, the Rwandan Genocide doesn't fully explain the increases (particularly in 1997). 

The 'change_life_exp' variable compares life expectancy in the target year with the life expectancy 5 year prior. So the life expectancy in 1997 is compared to life expectancy in 1992. When it comes to ranking these changes, a country with relatively low life expectancy in the comparison year are more likely to rank higher than a country with relatively high live life expectancy regardless of the investments either country made in general welfare. So what was happening in around 1992 is very relevant in explaining any increases in 1997.

Looking at Rwanda's life expectancy from 1980-2000 shows that life expectancy rapidly decreased between 1986 and 1993 (life expectancy actually rose in 1994 despite the genocide). This decrease isn't regional. the life expectancy in Sub-Saharan Africa was constant during this period.

I think a reasonable explanation for the decrease in life expectancy is HIV/AIDS. In 1983, Rwanda was among the first countries in the region to have [documented AIDS cases](https://www.thelancet.com/journals/lancet/article/PIIS0140-6736(84)90240-X/fulltext) (you can find the full text on scihub but I'm not linking that). By 1986, the disease had [spread widely](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2593071/#ref2) in rural areas where 83% of the population lives.

large improvements in healthcare in a country with where quality was historically poor, coupled with the AIDS epidemic can explain the large jump in life expectancy in 1997 that got Rwanda in the ranking.

**Comment by monsadan** [comment]
Rwanda have a movie that shows some of the civil war that have an impact in the population [Rwanda Hotel Trailer](https://www.youtube.com/watch?v=qZzfxL90100)

Cambodia also have a civil war that affect the population.

**Comment by schmimol** [comment]
Civil War in Cambodia 
Cultural Revolution in China 
In general disputes

**Comment by emonto15** [comment]
These countries had a really hard time, between civil wars, extreme poverty, and HIV/AIDS.
