### ISSUE TITLE
activity0104 FullTime_YearRound stats

### ISSUE THREAD

**Issue by Rand3rino** [STA518-Spring20/discussion#31]
For TODO3 where we are asked to find the median salary of full-time year-round (FTYR), I'm thinking that I need to weight the median of each major by the number of FTYR. But when it comes to the summarize(), I don't know which functions to use to get to the median.

Am I on the right train of thought with have a variable for median * FTYR?

**Comment by dirksem** [comment]
I believe if you look at the description of the variables that "median" is for full time year round workers.  You shouldn't need to use the ftyr variable, I believe. And I think new_variable = median(x) will give you the median.
