### ISSUE TITLE
Application 4: conditional relative frequencies

### ISSUE THREAD

**Issue by chycinsa** [STA518-Spring20/discussion#32]
I don't know how to do relative frequency in r with a given. Can you provide any references that could help?

**Comment by dykesb** [comment]
What have you looked at already?

**Comment by chycinsa** [comment]
I couldn't find anything in the book, and I couldn't find anyone using a given on my google searches.

**Comment by dykesb** [comment]
It might not use "given", but does a conditional frequency table or two-way contingency table sound more familiar?

**Comment by daymonjohnson** [comment]
Do you want us to find the relative frequency of how often the attack changes vs stays the same or a relative frequency of each attack? Or something different.

**Comment by dykesb** [comment]
Given a Pokémon's starting attack, what does the breakdown of their new attack look like (with respect to relative frequency)?

**Comment by emonto15** [comment]
attack_strong - attack_strong_new
          A           -              X
          A           -              Y
          B           -              Z
          B           -              Z

Then: 
           Relative Freq.
A-X = 0.5
A-Y = 0.5
B-Z = 1

Is this accurate?

**Comment by dykesb** [comment]
It won't looks like this (as we haven't learned how to pivot data yet), but this is an example image that shows up when I google "conditional relative frequency table":

![conditional relative frequency table](https://mathbitsnotebook.com/Algebra1/StatisticsReg/sportscartable4.JPG)
