### ISSUE TITLE
Application 4 (To-Do 3)

### ISSUE THREAD

**Issue by KhileahWilliams** [STA518-Spring20/discussion#33]
Im having a lot of trouble trying to filter. Can you let me know what's wrong with my code? 
![Screen Shot 2020-05-15 at 3 15 20 PM](https://user-images.githubusercontent.com/64782486/82087848-e64d4e00-96be-11ea-8bb4-e3f1b6733904.png)

**Comment by daymonjohnson** [comment]
I would use != "Eevee" but not sure why that way isn't working.

**Comment by dykesb** [comment]
You're not using your filtered dataset in your `ggplot()` call by specifying a dataset here (line 3).

**Comment by KhileahWilliams** [comment]
So do I put that filter statement after the ggplot()

**Comment by dykesb** [comment]
No, the `data = ` is unneeded. I see you closed this can you provide a summary of what you did?

**Comment by KhileahWilliams** [comment]
I removed "data=pokemon, mapping =" within the ggplot statement.

**Comment by dykesb** [comment]
For completeness, the `mapping = ` did not need to be removed.
