### ISSUE TITLE
Revisions

### ISSUE THREAD

**Issue by millerp217** [STA518-Spring20/discussion#34]
I noticed in the [Revision](https://sta518.github.io/courses/assessment/revision/) section of the syllabus that for the activities it says:
____
If you individually received a “Progressing” and wish to revise and resubmit, you will need to schedule an individual meeting with me. In this meeting we will talk about your preparation and performance. Individuals are only allowed one re-submission.
____
Is this only 'one re-submission' per activity or for the semester?

**Comment by dykesb** [comment]
Per semester. I hope that the discussion, should a student need to have one with me, should clear up my expectations.
