### ISSUE TITLE
Activity 2.1 contains() or ends_with() 

### ISSUE THREAD

**Issue by schmimol** [STA518-Spring20/discussion#35]
I'm struggling trying to reproduce the pivoted data using either contains() or ends_with(). I don't think we ever learned the code for that.

**Comment by dykesb** [comment]
They were in the Isolate rows/columns Primer and corresponding chapters. Remember you can always type `?function` (e.g., `?contains`) to see the general documentation and examples.

**Comment by schmimol** [comment]
ok thank you

**Comment by KhileahWilliams** [comment]
I'm also confused on the code to type for this, the ?contains isn't to helpful to me in understanding. Is that primer from the section were in (May 18-19)?

**Comment by dykesb** [comment]
This would be from the **May 11 and 12: Introduction to Data Pipelines** content.

**Comment by omarRmalik** [comment]
https://www.rdocumentation.org/packages/tidyselect/versions/1.0.0/topics/select_helpers
