### ISSUE TITLE
Activity 2.1 To-Do 6

### ISSUE THREAD

**Issue by KhileahWilliams** [STA518-Spring20/discussion#36]
Im having a lot of troubles understanding what to do with both chunks of r code. 
![Screen Shot 2020-05-19 at 1 34 31 PM](https://user-images.githubusercontent.com/64782486/82359296-b4e1c480-99d5-11ea-8852-8dbcdbf119f8.png)

**Comment by jasonrsmith99** [comment]
I doesn't look like the pipe function is recognized. Do you have the Tidyverse package loaded?

**Comment by dykesb** [comment]
Look at the `load-data`  code chunk  (the second one that I provided you) to see how to reading in `.csv` files and assign these to objects. You won't use a `%>%` to do this. Also, I recommend that you use `<-` instead of `=` to assign.

**Comment by KhileahWilliams** [comment]
okay I made some changes that now work. Why does read_csv not work?

![Screen Shot 2020-05-19 at 1 52 05 PM](https://user-images.githubusercontent.com/64782486/82360812-ee1b3400-99d7-11ea-9da9-9a4d6503f774.png)

**Comment by dykesb** [comment]
`read_csv()` should work if you follow @jasonrsmith99 recommendation. Also, see my recommendation about using `<-` instead of `=`.

**Comment by Rand3rino** [comment]
@KhileahWilliams looks like you accidentally used a period instead of an underscore in ```read_csv```. ```read.csv``` may be in a different package.

EDIT: I just tried ```read.csv``` and it works for me, also switched to ```=``` instead ```<-``` and didn't run into any issue. Can you share the error message?

**Comment by dykesb** [comment]
`read.csv()` is a base R package. Not wanting to go into too much of the detail, the tidyverse version (i.e., `read_csv()`) has some nice default behavior that you might need to fix using the base function.
