### ISSUE TITLE
Application 05 knitting issue

### ISSUE THREAD

**Issue by chycinsa** [STA518-Spring20/discussion#37]
When I run the chunk it works, but when I knit the document it is tell me that Size_Small doesn't exist. I've never run into this problem before. Can you help me figure out what to do in this situation?

**Comment by chycinsa** [comment]
![image](https://user-images.githubusercontent.com/64855912/82359896-89130e80-99d6-11ea-9be0-c5bda9a64075.png)

**Comment by dykesb** [comment]
If you look at the `rename-plu` code chunk, I included a code chunk option that says `eval = FALSE`. If you remove this chunk after you do **3. Read in the data**, everything should knit.

FWIW: The option tells R Markdown not to evaluate the code chunk.
