### ISSUE TITLE
Clarification in Activity 2.2 Challenge 1

### ISSUE THREAD

**Issue by emonto15** [STA518-Spring20/discussion#40]
**Context**:  Challenge 1 says: '(...) Can you do `r emo::ji("ballot_box_with_check")` To-Dos 3 and 4 in one pivot instead of pivoting, then splitting?'
**Question:** When you say **one pivot** you mean that we **cannot** pipe more functions? So just by using one of either `pivot_wider(...)` or `pivot_longer(...)`, we should be able to achieve the same result as both to-dos?

Thanks!

**Comment by dykesb** [comment]
Can you do the separating within the pivot? You should have the same output as you go by doing To-Dos 3 & 4. Look at some of the additional function arguments and examples ([`pivot_longer()`](https://tidyr.tidyverse.org/reference/pivot_longer.html) and [`pivot_wider()`](https://tidyr.tidyverse.org/reference/pivot_wider.html) )

**Comment by emonto15** [comment]
Ok, so I managed to make it 'work'. However, I have a problem: the pivot function cannot handle when two columns are named equal. For instance, when we separate `bty_m1upper` and `bty_m2upper` both will be separated as `bty_m` & `upper`. Then the function will only use one of them, leaving the other out. I already compared it with my `separate` function that is working, and parameters that have the same meaning have the same values.

**Comment by dykesb** [comment]
I do not know what you mean by "when two columns are named equal." Can you provide more information?

**Comment by emonto15** [comment]
when we separate `bty_m1upper` using `1` as the separator, the result will be 2 temporal columns named `bty_m` and `upper`. We also have a column named `bty_m2upper`, and again if we separate that using `2` we will have `bty_m` and `upper`. So we end up with 2 columns (one for the 1 and one for the 2) named `bty_m`  and 2 columns named `upper`. Both may coexist at the same time in memory (I don't really know because the `separate` function must have the same issue, but it manage to create the 2 rows instead of only 1)

**Comment by dykesb** [comment]
Is there a way to pass multiple separator options? Or separate on all digits (i.e., 0-9)?

**Comment by emonto15** [comment]
yes, I'm using a regular expression `\\d` this detects digits

**Comment by dykesb** [comment]
Without really knowing which arguments (and how) you are using this, it is difficult to provide insight.

If you're using `names_to` and `names_sep` combo, `names_sep` specifies when to split the column and you would need to set unwanted columns to blank.

If you're using `names_to` and `names_pattern` combo, `names_pattern` needs to know what to keep (within `( )`) and what to get rid of (between `( )`).

**Comment by emonto15** [comment]
These are my params: `names_sep = '\\d',names_to = c("student_gender","student_level"), values_to = 'bty_rating')` do you see anything usual?

**Comment by dykesb** [comment]
`names_sep` asks for when to separate (i.e., what character index). So if you want to separate around the number value in the string, you would separate the string at 2 and 3 and set the middle name to `NA` (if you separate a string at 2 places you have 3 columns. For example, "splitat6and8" with `names_sep = c(6,8)` becomes "split" "at" "6and8". So I would need to have `names_to = c("first", NA, "values")` and the "at" column wouldn't show.

Try using `names_pattern = "(.)\\d(.*)"` instead. This pattern says "keep the first value "`(.)`", remove digit value "`\\d`", keep the next value and everything afterwards "`(.*)`". You would only need two `names_to` values using this method. If I wanted to also keep the digit value, I would put that in within parentheses and my `names_to` argument would need another value.
