### ISSUE TITLE
Activity 2.2 bind columns

### ISSUE THREAD

**Issue by jasonrsmith99** [STA518-Spring20/discussion#41]
I've confirmed that the objects 'evals_id' and 'evals_means' have the same number of observations and are arranged by course_id. When I run the code

```r
bind_cols(evals_id, evals_means$mean_bty_rating)
```
I get and error message that says "Argument 2 must have names." I understand that R doesn't like _'evals_means$mean_bty_rating'_ but I can't figure out why.

**Comment by dykesb** [comment]
Try `evals_means %>% select(mean_bty_rating)` (or `select(evals_means, mean_bty_rating)`) instead of `evals_means$mean_bty_rating`...

**Comment by jasonrsmith99** [comment]
That works. I was a bit confused since the hinted mentioned evals_means$mean_bty_rating.

**Comment by dykesb** [comment]
I'll update this in my version (thought the `$` method would work). I'll try to see if I can figure out why that doesn't work and respond here when I do.

**Comment by dykesb** [comment]
Using the `$` method doesn't work because this produces a numeric vector and `bind_cols()` needs a `data.frame` or `list` object. One way to force this to work is by putting the `$` call in a `list()`:

```
bind_cols(evals_id, list(mean_bty_rating = evals_means$mean_bty_rating))
```

Next week we will see better ways to join datasets.
