### ISSUE TITLE
Application 06 #5

### ISSUE THREAD

**Issue by bakjinn** [STA518-Spring20/discussion#43]
<img width="320" alt="Screen Shot 2020-05-22 at 11 34 05 AM" src="https://user-images.githubusercontent.com/23545297/82684245-43498680-9c20-11ea-88b3-bf0c57495d54.png">
I'm getting an error in as.POSIXlt. I'm not sure why it's failing.

**Comment by dykesb** [comment]
You don't need to use the **lubridate** package to convert it to date format, just `separate()` the `date` column for now. We'll see how to handle date/times next week.
