### ISSUE TITLE
Application06 number 6 option A

### ISSUE THREAD

**Issue by sharnjitvirk** [STA518-Spring20/discussion#44]
1.  I was able to make a tibble with a summary value. Are we supposed to do the mean values of Size_Large for each region or are we supposed to do a sum? Or maybe a different value?

2.  I'm confused for what the scatter plot axes are supposed to be. Is it supposed to be one region and another or is it supposed to be multiple layers of geom_point for each region's values over year?

**Comment by dykesb** [comment]
1.	You can use whatever summary you want.
2.	You should have at least two columns where these columns are the same measure for different markets. For your scatterplot, one axis should the measure for one market and the other axis for the other market.

**Comment by sharnjitvirk** [comment]
Thank you!
