### ISSUE TITLE
Error message when trying to knit 6A from Application 06

### ISSUE THREAD

**Issue by jaydfox** [STA518-Spring20/discussion#45]
Anyone know how to fix this error. This happens when I try to knit 6A for application06.
![image](https://user-images.githubusercontent.com/7217168/82708095-72c1b880-9c4b-11ea-996e-aa47619124c1.png)

**Comment by dykesb** [comment]
The, "The column `Size_Large` doesn't exist." comment in this error message makes me think you still have `eval = FALSE` specified in chunk I provided you earlier in the file. Look to see if you do.
