### ISSUE TITLE
App. 6, part 7

### ISSUE THREAD

**Issue by NickDuley** [STA518-Spring20/discussion#46]
I am having trouble with getting the mean function from values_fn to apply to both small and large avocados in pivot_wider(). Has someone gotten this to work for themselves?

![image](https://user-images.githubusercontent.com/44388145/82710522-0fd32000-9c51-11ea-9502-b4df2be1e32a.png)

**Comment by dykesb** [comment]
Can you provide an update to how you fixed this?
