### ISSUE TITLE
Activity 2-3 Submission Date

### ISSUE THREAD

**Issue by Hab25blu** [STA518-Spring20/discussion#49]
What is the submission deadline for Activity 203? Is this also Midnight Wednesday like Application 7?

**Comment by dykesb** [comment]
I grade Application Tasks (ATs) first so these should be prioritized as I assess these for "correctness", but having worked through the Activities will help you complete the ATs. If an activity isn't completed when I assess them (for completeness), your team simply needs to email me when it has been completed and I will recheck it. The only real issue with "late" activities is if an individual did not contribute to their team's submission.

I expect that you are completing the Activities in the same time period as the ATs and will originally assess them after the corresponding AT due date.
