### ISSUE TITLE
Application 1 output question 

### ISSUE THREAD

**Issue by schmimol** [STA518-Spring20/discussion#5]
For the analysis part of the assignment when I try to "run" the code, I can see the output displayed (which we would use to notice the patterns). But for the first question about how many movies there are, there is no output, so do we get that information just from looking at the article itself?

**Comment by dykesb** [comment]
I forgot to add a printout `bechdel090_13` during the chunk in lines 26 - 29 of the `.Rmd` file. If you feel comfortable adding to this code chunk, update it so the complete R code (between the ` ``` `) looks like this:

```
bechdel90_13 <- bechdel %>% 
  filter(between(year, 1990, 2013))

bechdel90_13
```

Otherwise, it is OK to use the information that gets printed in the sentence prior to this code chunk (that corresponds to line 24 of the `.Rmd` file).

I have updated this in the `.Rmd` file if you created your Application 1 **after 2:30 pm** on May 5.
