### ISSUE TITLE
filter() question

### ISSUE THREAD

**Issue by schmimol** [STA518-Spring20/discussion#50]
I know %in% filters things “in”, but how do you filter things “out” that are not in? I’ve tried %notin% and using “-“ and “!” in front as well but can't figure out how to get it to work.

**Comment by jasonrsmith99** [comment]
I've had luck doing
```
filter(!(var1 %in% var2))
```

**Comment by dykesb** [comment]
@jasonrsmith99 showed one way! I'll use `var` to represent a column in a dataset called `dat`. I'll use `vec` to stand for either a single term (e.g., `vec <- "yellow"`) or a vector containing multiple terms (e..g, `vec <- c("yellow", "blue", "red")` ).

This is a repeat of what Jason showed:

```
dat %>% filter( !(var %in% vec) )
```

This is an alternative way:

```
dat %>% filter( !var %in% vec )
```

Later in the semester, we will see how to define our own functions so you could create your own `%notin%` operator.

**Comment by schmimol** [comment]
got it thanks!
