### ISSUE TITLE
Geography Visual

### ISSUE THREAD

**Issue by Rand3rino** [STA518-Spring20/discussion#53]
Anyone have any luck with the map visual? What libraries are you using?

The [urbnmapr](https://urbaninstitute.github.io/urbnmapr/articles/introducing-urbnmapr.html) library I sent in the chat in today's lecture has alaska and hawaii south of texas so I'm looking for a more geo-accurate projection. I found [rnaturalearth](https://www.r-spatial.org/r/2018/10/25/ggplot2-sf.html) which I can plot the whole world but when I was to plot the states, it asks for rnaturalearthhires. This isn't supported on RStudio's cloud version.

**Comment by jasonrsmith99** [comment]
I was able to use the [tigris](https://cran.r-project.org/web/packages/tigris/index.html) package and some creative filtering to make something "functional." I wrote down my thought process [here](https://github.com/jasonrsmith99/alaska-hawaii-mapping/blob/master/Alaska-Hawaii-Mapping.md).

Currently, I'm just using the shapefile of the lower 48 from the _map_data_ function and not worrying about it :upside_down_face:

**Comment by dykesb** [comment]
Check out `states <- map_data("world") %>% filter(region == "USA")`.

If you want to zoom in, check out the `scale_x_continuous(limits = c(<lower>, <upper>))` layer.

**Comment by Rand3rino** [comment]
I found out another way to zoom in. Inside the geom_polygon for states, use x = -abs(long) to get the archipelago to show up near Alaska.
