### ISSUE TITLE
Lack of 'emo' package and How to install it

### ISSUE THREAD

**Issue by NickDuley** [STA518-Spring20/discussion#55]
I had an issue with the 'emo' package not being present for the activity due tonight, and while I was able to find the solution, having the resources here would be easier than finding it every time i's needed.

1. Install the devtools package ( install.packages('devtools'))
2. Copy and paste the following code into the console: devtools::install_github("hadley/emo")
3. Congrats. You now can use emotes

**Comment by shroom552** [comment]
Where should we install the devtools package? We aren't suppose to use install in our .rmd due to code etiquette.

**Comment by NickDuley** [comment]
Just install it into the console like if you were to install tidyverse manually (e.g install.packges("tidyverse"))

**Comment by dykesb** [comment]
Duplicate of #8
