### ISSUE TITLE
Issue when trying to display map of US

### ISSUE THREAD

**Issue by chycinsa** [STA518-Spring20/discussion#57]
![image001-1](https://user-images.githubusercontent.com/64855912/83080102-68d4f680-a04b-11ea-9730-41d44de74b70.png)
Ran into this issue while trying to view my graphic. Had to exit Rstudio and reopen my project to get the image to display.

**Comment by dykesb** [comment]
Sometimes RStudio loses connection to the server it is working from and a restart should solve this.
