### ISSUE TITLE
R Studio Update to Version 4.0.0

### ISSUE THREAD

**Issue by ralythompson24** [STA518-Spring20/discussion#60]
Hi Everyone,

Today I started working on **Activity 0204** and when logging into RStudio I was prompted to install updates, which I did. I found when I started working many of the packages I had been using were not available, and when I tried to knit my document I got the following error: 

![image](https://user-images.githubusercontent.com/64804055/83170330-5e197080-a0e2-11ea-8f9b-5b07af3254d0.png)

I tried re-installing some of the packages I was missing, but got this error:

![image](https://user-images.githubusercontent.com/64804055/83170285-4e9a2780-a0e2-11ea-8e2e-f08b4296e656.png)

Everything seemed to be fine when I switched back to **R Version 3.6.3** in the top right corner of the RStudio console, so if you experience these issues try that  ¯\\\_(ツ)_/¯ 

Maybe Bradford can speak to this a little more.

**Comment by dykesb** [comment]
Hadley's **emo** package isn't on CRAN (the Comprehensive R Archive Network - where R packages are usually submitted for release), so to install it, you need to actually get it from his GitHub repo (see #55 ). The **tidyverse** and **here** packages are all on CRAN so those were probably included in their recommended updates.

I don't know why RStudio Cloud updated their version (I would hope this would be an option that I as the instructor would be asked about), but it is nice that you can still switch back to previous versions.

I will update the default Project to have **emo** installed right now!

**Comment by ralythompson24** [comment]
Ahhh that makes sense. Thank you! 😁

**Comment by dykesb** [comment]
R 4.0.0 on our RStudio Cloud should now have the **tidyverse**, **here**, and **emo** installed and read to `library()`.
