### ISSUE TITLE
acitivity 0204: Making bar chart

### ISSUE THREAD

**Issue by chycinsa** [STA518-Spring20/discussion#64]
I am unable to make the bar chart when I include label=TRUE, I can make the graph when the month stays as a number, but not when it is "July", etc.

**Comment by Rand3rino** [comment]
The documentation for [lubridate::month](https://www.rdocumentation.org/packages/lubridate/versions/1.7.8/topics/month) has the option as "label". Must have just been a typo

**Comment by dykesb** [comment]
@chycinsa Randy's comment was about my typo, not yours. Did his comment help you fix this?

**Comment by chycinsa** [comment]
No, but I used count() instead of sum() and it worked
