### ISSUE TITLE
Activity0204 To-Do 4

### ISSUE THREAD

**Issue by NickDuley** [STA518-Spring20/discussion#66]
Is there something I am missing when it comes to this code? I can't seem to get the NAs to filter out

![image](https://user-images.githubusercontent.com/44388145/83219823-59cf7080-a13f-11ea-92a4-c40ec78b238e.png)

**Comment by dykesb** [comment]
`is.na()` is looking for an argument, you've provided none. Pass it a column name.

**Comment by NickDuley** [comment]
Upon giving an argument for is.na(), I get the following error

![image](https://user-images.githubusercontent.com/44388145/83274683-122b0200-a19c-11ea-90c6-dba46a7132c5.png)

**Comment by dykesb** [comment]
EventDate isn't "missing" until you apply `ymd()` ...

**Comment by NickDuley** [comment]
So it would be:
1. ymd() to EventDate
2. Find the NAs in EventDate
right?

**Comment by dykesb** [comment]
Try it out.

**Comment by NickDuley** [comment]
I got it to work
