### ISSUE TITLE
Activity 0204 to-do 6

### ISSUE THREAD

**Issue by hayley-chelotti** [STA518-Spring20/discussion#67]
For this question, do you want us to calculate the total number of events *in each year* for 'min_date' and 'max_date' or the *cumulative total number of events* up until each time point?

**Comment by dykesb** [comment]
For each theater.

**Comment by hayley-chelotti** [comment]
Ok, thank you.

**Comment by hayley-chelotti** [comment]
It seems like when I use this code, both the min() function and the max() function return the earliest date on file, and it is not grouped by theater. 

*london_stage%>%
  filter(TheatreCode!="none")%>%
  group_by(TheatreCode)%>%
  summarise(total_events=n(),
            min_date=min(EventDate),
            max_date=max(EventDate))%>%
  arrange(desc(total_events))->london_stage_theater*

I'm not sure why, but now when I run it I get the following error:

*Error in UseMethod("filter_") : no applicable method for 'filter_' applied to an object of class "Date"*

**Comment by dykesb** [comment]
When I run your code, here is the output I get (and no error):

```
# A tibble: 233 x 4
   TheatreCode total_events min_date   max_date  
   <chr>              <int> <date>     <date>    
 1 dl                 18451 1674-03-26 1800-06-18
 2 cg                 12826 1662-05-09 1800-06-16
 3 hay                 5178 1720-12-29 1800-09-16
 4 king's              4299 1714-10-23 1800-08-02
 5 lif                 4117 1661-06-28 1745-10-07
 6 gf                  1832 1729-10-31 1772-10-23
 7 queen's              884 1705-04-09 1714-06-23
 8 marly                403 1750-08-16 1776-08-10
 9 bf                   257 1661-08-22 1767-09-07
10 dg                   235 1671-06-26 1706-11-28
# ... with 223 more rows
```

Try restarting R (Drop down menu: Session > Restart R) to see if this helps...

**Update**: Forgot to format EventDate. Output has been corrected.

**Comment by hayley-chelotti** [comment]
I restarted R and now get this error when I run it:

*Error in london_stage %>% filter(TheatreCode != "none") %>% group_by(TheatreCode) %>%  : 
  could not find function "%>%"*

**Comment by dykesb** [comment]
You re-ran `library(tidyverse)` (and the other packages), correct?

**Comment by hayley-chelotti** [comment]
Yes, it worked when I re-started R again and re-ran that chunk.
