### ISSUE TITLE
Issue while trying to join my team assigment (Activity 1.2)

### ISSUE THREAD

**Issue by emonto15** [STA518-Spring20/discussion#7]
I was trying to do activity 1.2, and apparently my team is already created, but I don't have the option to join my team. 
![image](https://user-images.githubusercontent.com/14222572/81216231-9973c400-8fa8-11ea-950d-5a49b30e9af8.png)

**Comment by Rand3rino** [comment]
I my view is exactly like this picture and it won't let me add the team.

**Comment by monsadan** [comment]
Same issue here

**Comment by dykesb** [comment]
Give it a try now. I deleted the teams that I created in the Organization yesterday... maybe this was causing issues.

**Comment by dykesb** [comment]
Looks like it is...
