### ISSUE TITLE
Activity 2.5 Dataset issue

### ISSUE THREAD

**Issue by emonto15** [STA518-Spring20/discussion#70]
There are a bunch of songs that are messed up. Because the `read_tsv()` didn't split `title` and `artist` properly.

![image](https://user-images.githubusercontent.com/14222572/83436296-3ccac400-a403-11ea-8039-a0c656277afe.png)

How are we going to deal with that?

Thanks.

**Comment by dykesb** [comment]
I'll try to explore why `read_tsv` this isn't working, but this worked for me:

```
read.table(here::here("data","billboard_songs.txt"), header = TRUE)
```

**Comment by dykesb** [comment]
I fixed the issue for later clones, but recommend using this method if you already started. It looks like the `escape_backslash` option isn't currently available in `read_tsv()`.
