### ISSUE TITLE
activity0205 "featuring" and "feat"

### ISSUE THREAD

**Issue by dirksem** [STA518-Spring20/discussion#72]
I am seeing some entries say "feat" instead of "featuring".  Are we supposed to worry about those entries for "most featured?"  Also, I am seeing some of the "collaborated" split by "with" in addition to "," and "&".  Should we correct "feat" and "with" for the "collaborated" part also? Or should we just ignore the entries with "feat"?  Also, "MUMFORD & SONS" becomes "MUMFORD" "SONS".  Do we worry about these?

**Comment by dykesb** [comment]
Text data can get real messy real quick. You are not expected to do anything beyond what I explicitly stated, but you are welcome to catch as many as you can (unintended Pokémon joke).

**Comment by dirksem** [comment]
Am I missing an easy way to count the distinct character values in a vector?  Probably a simple question but can't find any internet sources to help.

**Comment by jasonrsmith99** [comment]
I converted the vector into a tibble with as_tibble( ) and used summarize( ) for calculations.

**Comment by dirksem** [comment]
Thanks Jason I will try that route!
