### ISSUE TITLE
str_extract_all not working in 2.5

### ISSUE THREAD

**Issue by monsadan** [STA518-Spring20/discussion#73]
I'm trying to use the `str_extract_all()` to find the most collaborated artist in the activity but I'm getting a weird response for the code. This is mi code:

billboard_songs %>% pull(artist) %>% 
  str_replace_all("featuring (.*)", "") %>% 
  str_extract_all("&|,")

When I run to verify that works this is what I get:
[[668]]
character(0)

It seems that it's not reading the values of the vector, I also try to use the simplify parameter to see if there is any effect but don't do much.

From the documentation I don't see any other parameter to add.

Is any other parameter?

Thanks

**Comment by dykesb** [comment]
I used `[^&,]+` to keep everything not `&` or `,`:
- `[^` Match any character not in this pattern,
- `&` matches for this character,
- `,` matches for this character, 
- `]` closes the pattern
- `+` matches 1 or more of the pattern

You're code was correctly picking everything that was `&` or `,`.
