### ISSUE TITLE
Application 6 #6B

### ISSUE THREAD

**Issue by bakjinn** [STA518-Spring20/discussion#74]
<img width="292" alt="Screen Shot 2020-06-02 at 1 37 23 PM" src="https://user-images.githubusercontent.com/23545297/83551373-46712c00-a4d6-11ea-9ed7-7c0bd2bb0ee9.png">
My line graph is not showing up the way I was hoping. Does anyone know where I'm going wrong?

**Comment by dykesb** [comment]
Your `select()` portion is not doing what you intended it to do. What were you hoping to do with this statement?

**Comment by bakjinn** [comment]
I was trying to only select the smallest of the large avocados.

**Comment by dykesb** [comment]
If you do this, you will only get one observation and there would be no need to plot this: line graphs need multiple values.  Also, `select()` would not be the function to use as you are trying to `filter()` the data to keep only the smallest value. 

If you are trying to "compute some measure of `Size_Large`", then you would do this within a `summarise()` or `summarize()` function.

**Comment by bakjinn** [comment]
How would I get the min of large avocados for each year?

**Comment by dykesb** [comment]
What have you looked into to help you with this?

**Comment by bakjinn** [comment]
I have tried to search the web and the book but I am not sure what a good resource would be.

**Comment by dykesb** [comment]
What have you searched for?

**Comment by bakjinn** [comment]
Using summarize and how to get one row per year in r, I went to chapter 12 since that was the reading for the week this was assigned. I am not fully sure how to get a column without redundant rows while consolidating the other rows.

**Comment by dykesb** [comment]
We've been working with `summarise()` since Activity 1.3 (i.e., [Section 5.6](https://r4ds.had.co.nz/transform.html#grouped-summaries-with-summarise) of the text).
