### ISSUE TITLE
Midterm Project removing (pt.)

### ISSUE THREAD

**Issue by chycinsa** [STA518-Spring20/discussion#76]
I'm struggling to get population to become a data frame again after using `str_replace_all`. I tried using `unlist()` and `as_tibble()` but neither seemed to work.

**Comment by dykesb** [comment]
You can use `str_...()` functions within a `mutate()` step to edit a column within a tibble.

**Comment by chycinsa** [comment]
There are lots of rows where it might be "Orange County" and then "Balance of Orange County". Do I treat these as separate rows or should I remove the balance and combine them?
