### ISSUE TITLE
Midterm issue with gtd and poverty

### ISSUE THREAD

**Issue by emonto15** [STA518-Spring20/discussion#79]
While joining `gtd` and `poverty` I found that `poverty` does not have **123** cities that are in `gtd` (out of 146). I checked this manually too: copying the city name from `gtd`, and pasting it in `poverty` unmodified dataset. Is this normal?

![image](https://user-images.githubusercontent.com/14222572/83656091-bdfd9480-a584-11ea-8d07-a2d371670db8.png)

In the pic `gtd` already has `population` joined.

Thanks.

**Comment by dykesb** [comment]
`poverty` doesn't have **any** city-level information, it is all by state-county-level...

**Comment by emonto15** [comment]
Is it a good idea trying to fill the `NA`s values in fields like `pop2015` or `PCTPOVALL_2015`, etc., with the county values (whenever the city is not in `poverty` or `population`)?

**Comment by dykesb** [comment]
If you decide to do this, you need to provide justification/reasoning behind this choice.
