### ISSUE TITLE
Activity 1.2 no package called 'emo'

### ISSUE THREAD

**Issue by jasonrsmith99** [STA518-Spring20/discussion#8]
When I tried to knit this assignment, I got the following error.

![image](https://user-images.githubusercontent.com/64434718/81223907-d5ad2180-8fb4-11ea-864e-6850230ee163.png)

This seems to be because the markdown uses emojis that aren't natively supported.

I was able to fix this by installing the package, '_emo_', that add emoji support.

The prerequisite package you'll need is _'devtools'_. This will let you install packages from github repos (where the _emo_ package is.)

In the console, type in the following code:

>install.packages('devtools')

The second package is _'emo'_. This one is what actually let's you put emojis in markdown files.

In the console, type in the following code:

>devtools::install_github('hadley/emo')

once this package was installed, I was able to knit the file.

**Comment by dykesb** [comment]
Shoot, I forgot about these icons! I have updated the starter RStudio Project to avoid this for future activities, but for this activity you will probably need to follow the exceptional directions laid out by @jasonrsmith99 if you have already created an RStudio Project for this activity. 

If you have yet to create an RStudio Project for Activity 1.2, I believe this shouldn't be an issue.

**Comment by bakjinn** [comment]
Thanks Jason! I had the same issue and your solution worked for me!

**Comment by LauraRK** [comment]
I added it to my Rmarkdown where the library is called.  I ran it once then commented it out.  I do this to remind myself when I come back later in case I move to a different platform but it is probably cleaner to just run it in the console.  Thank you Jason!

**Comment by dykesb** [comment]
To add to @LauraRK 's comment, on lines 30-32 of the `activity0102-visualization-basics.Rmd` file which are currently: 

```
```{r load-package, message=FALSE}
library(ggplot2)
```

She updated this to be:

```
```{r load-package, message=FALSE}
install.packages("devtools")
devtools::install_github('hadley/emo')
library(ggplot2)
```

She ran this code (by either clicking on the green play button on the right-hand portion of this code chunk or pressing Ctrl+Enter on each of these lines, then commented out these lines with the `#` symbol as follows.

```
```{r load-package, message=FALSE}
#install.packages("devtools")
#devtools::install_github('hadley/emo')
library(ggplot2)
```
