### ISSUE TITLE
Midterm Cleaning

### ISSUE THREAD

**Issue by chycinsa** [STA518-Spring20/discussion#80]
I created a vector of all the city names in GTD, and then filtered population using `%in%` said vector, but I'm only getting a handful of matches. But when I join the datasets by city, I get hundreds of matches. Is there anything that would make sense as to why they match one way, but not another?

**Comment by dykesb** [comment]
That would depend on how you are joining them.  Also, nrows(population) substantially larger than nrows(GTD).
