### ISSUE TITLE
RStudio Cloud will not let me save my changes

### ISSUE THREAD

**Issue by hayley-chelotti** [STA518-Spring20/discussion#81]
It has been a while since I pushed my changes on the midterm project, but now I keep getting this message:

<img width="381" alt="Screen Shot 2020-06-03 at 8 11 06 PM" src="https://user-images.githubusercontent.com/56937684/83701053-7ef82f00-a5d6-11ea-8e32-e32f9a6199a8.png">

I restarted R and I continue to get that message each time I try to type something in. I can't save my changes and I am worried that I am going to lose all of my progress. 

Do you have any insight as to what might be going wrong here and how I could try to fix it?

**Comment by dykesb** [comment]
It might be a server timeout issue. Can you still view your files? Worst case is to copy-paste into a new RStudio project. I'm not around my computer right now, but I can look into your project tomorrow morning.

**Comment by hayley-chelotti** [comment]
I could not view my files or knit, but I was able to push my .Rmd file to GitHub after closing the window and reopening the project in a new RStudio window. I am using a different computer now and have just started to have the same issue.

**Comment by dykesb** [comment]
I think it's working on another computer is because the Amazon Web Server that you were connected to in your previous session had disconnected and when you tried to save, there wasn't a "machine" attached to your session. This would be a good opportunity for me to encourage you all to save frequently and log-out when you aren't working so that these issues don't occur. Also, you can [relaunch your project in your session](https://community.rstudio.com/t/rstudio-cloud-pop-up-error-saying-no-such-file-or-directory/48767)

**Comment by omarRmalik** [comment]
You can save a copy of your Rmd locally by using the export option under More right bottom corner.

**Comment by millerp217** [comment]
![image](https://user-images.githubusercontent.com/48660841/83977940-0e9d2680-a8d2-11ea-8cab-ff1df6c43251.png)

@dykesb  I'm having similar issues.  I've relaunched the project several times, cleared cache, was able to knit, and push to git.  However, every time I relaunch and re-run all of my code blocks I get the error message above when I get to a specific block for a join.  

Followed by the crash error 
![image](https://user-images.githubusercontent.com/48660841/83978024-a0a52f00-a8d2-11ea-8df2-34e7804d17d4.png)

**Comment by millerp217** [comment]
I may have gotten around this by using a merge() instead of a left_join().

**Comment by dykesb** [comment]
@millerp217 By "relaunching" do you mean the  `...` > "Relauch Project" method?

Is this an issue only when you try to join?

**Comment by millerp217** [comment]
Yes that was the relaunch method I was referring to.

Yes it was only when I tried to Join but I was able to get the Merge to work for that step. I believe, for my part of this issue at least, I believe my comment may be more in line with #94 .

**Comment by dykesb** [comment]
Gotcha. Then you might want to be intentional with how you are joining the datasets.  If you think back to "Lucy's Hack" that you did a couple of Application Tasks ago, if you have a smaller (with respect to number of rows) table of "lookup values", that should be joined to the larger table.
