### ISSUE TITLE
Activity 3-1 

### ISSUE THREAD

**Issue by Hab25blu** [STA518-Spring20/discussion#82]
I am having issues reading in the csv for 3.1.

`RatSightings <- read_csv(here:here("data", "Rat_Sightings.csv") )`

Its throwing me the error
`Error in here:here("data", "Rat_Sightings.csv") : NA/NaN argument`

**Comment by dykesb** [comment]
Did you upload the `Rat_Sightings.csv` file from Bb to a `data` folder?

**Comment by Hab25blu** [comment]
No, I wanted to try downloading it via R code and loading it that way. i was able to bring it into the data folder but when i tried to read it into R it threw that error.

So i tried to load it in that way as well, but it threw the same error.

**Comment by dykesb** [comment]
Then the issue is probably how you're downloading it. How did you do this?

**Comment by Hab25blu** [comment]
Not sure what changed, but its working now. Re-downloaded the file and its no longer throwing that error.
