### ISSUE TITLE
Filtering Issue

### ISSUE THREAD

**Issue by NickDuley** [STA518-Spring20/discussion#85]
Maybe I'm not seeing something right, or I have forgotten soemthing but I am trying to filter this New York data set by sepcific counties for the boroughs, but I am only getting 20 obs when I know for sure there are more than 20.  Any advice?

![image](https://user-images.githubusercontent.com/44388145/83824247-ee882000-a6a3-11ea-8975-245608f61eee.png)
![image](https://user-images.githubusercontent.com/44388145/83824265-fc3da580-a6a3-11ea-9529-9b4ad0d92bda.png)

**Comment by dykesb** [comment]
See what happens with `%in%`

**Comment by NickDuley** [comment]
That was the issue. Thanks. One other thing, is there a way to connect points in geom_point by a group?

**Comment by dykesb** [comment]
Can you create a new issue for this?
