### ISSUE TITLE
Application 4 #4 no applicable method for `summarise`

### ISSUE THREAD

**Issue by bakjinn** [STA518-Spring20/discussion#86]
<img width="446" alt="Screen Shot 2020-06-05 at 1 28 45 PM" src="https://user-images.githubusercontent.com/23545297/83905977-ab27c300-a730-11ea-8f6b-e22f15c4acab.png">

I am getting an error with my summarize line. I am not sure what the error means.

**Comment by dykesb** [comment]
The issue is with the `count()` function.  `count()` is a wrapper for `group_by(data, var) %>% summarise( n = n(var))`. What are you trying to do in line 81?

**Comment by bakjinn** [comment]
I am trying to get the percentage of height change by dividing the number of pokemon by the number of pokemon that have grown.

**Comment by dykesb** [comment]
In general cases, calculating it this way will result in your numerator being larger than your denominator (so you would have values larger than 1 / 100%).

**Comment by bakjinn** [comment]
<img width="442" alt="Screen Shot 2020-06-05 at 1 51 31 PM" src="https://user-images.githubusercontent.com/23545297/83907595-b0d2d800-a733-11ea-8022-8f0fdc6cff9c.png">
I tried to incorporate your feedback but I have a new error for my summarize function.

**Comment by dykesb** [comment]
[`count()` is not the function to use here](https://github.com/STA518-Spring20/community/issues/86#issuecomment-639657769) because it needs a dataset and a variable specified.

**Comment by bakjinn** [comment]
Should I only select pokemon that grew and divide that by nrows(pokemon)?

**Comment by dykesb** [comment]
I believe that I did something similar in the [recreating-gapminder](https://github.com/STA518-Spring20/recreating-gapminder) repo.
