### ISSUE TITLE
Application 4 #4 height_change not found

### ISSUE THREAD

**Issue by bakjinn** [STA518-Spring20/discussion#87]
<img width="442" alt="Screen Shot 2020-06-05 at 1 34 46 PM" src="https://user-images.githubusercontent.com/23545297/83906373-70725a80-a731-11ea-887d-d03c9098f1a7.png">

I am not sure why my new variable 'height_change' is not being recognized.

**Comment by dykesb** [comment]
You haven't added it in `pokemon`.

**Comment by bakjinn** [comment]
Am I suppose to use cbind() to add a height_change column?

**Comment by dykesb** [comment]
You created a variable on line 92, but you didn't "make it stick". How can you save an object to R?
