### ISSUE TITLE
Connecting Points within geom_point()

### ISSUE THREAD

**Issue by NickDuley** [STA518-Spring20/discussion#88]
I was able to outline the boroughs with location points, but applying lines to make each borough's boundry more clear would be beneficial to map. Is there a way to do this within geom_point() or any other ggplot2 function?

![image](https://user-images.githubusercontent.com/44388145/83908013-61d97280-a734-11ea-9eb0-8159c45cbbaf.png)

Here is my current code for reference:

![image](https://user-images.githubusercontent.com/44388145/83908119-8b929980-a734-11ea-8388-86f2a3ce2302.png)

**Comment by dykesb** [comment]
`geom_polygon()`?
