### ISSUE TITLE
as.yearmon in midterm

### ISSUE THREAD

**Issue by dirksem** [STA518-Spring20/discussion#90]
I am using as.yearmon on the midterm and loaded the "zoo" package first, and the code chunk is running error free and produces my time series graphs.  However, when I go to knit, I am getting an error that function as.yearmon is not found.  Any ideas?

**Comment by dykesb** [comment]
Have you loaded it in your Rmd file (as opposed to within your Console)? Otherwise, is there an error that gets displayed?

**Comment by dirksem** [comment]
I restarted and ran all of my code chunks, but still get the error when knitting.

`summarise()` regrouping output by 'individual' (override with `.groups` argument)
Quitting from lines 386-409 (midterm-project01.Rmd) 
Error in as.yearmon(date) : could not find function "as.yearmon"
Calls: <Anonymous> ... <Anonymous> -> f -> scales_add_defaults -> lapply -> FUN
Execution halted


Now, at the beginning of the knit it is giving tidyverse errors too.

Attaching package: 'lubridate'

The following objects are masked from 'package:base':

    date, intersect, setdiff, union

Installing package into '/home/rstudio-user/R/x86_64-pc-linux-gnu-library/4.0'
(as 'lib' is unspecified)

**Comment by dykesb** [comment]
This looks like **zoo** isn't loaded in the session. Verify that you did the following when installing and loading **zoo**:

1. In your **Console**, you typed and ran `install.packages("zoo")`
2. In your `.Rmd` file, you typed `library(zoo)` (probably where you did this for **tidyverse** to keep everything organized).

**Comment by dirksem** [comment]
That was my issue, didn't realize the proper steps...after how long now?? lolol

Thank you!

**Comment by dykesb** [comment]
There are still silly things that I forget (like loading packages).
