### ISSUE TITLE
Loading data activity 0302

### ISSUE THREAD

**Issue by dirksem** [STA518-Spring20/discussion#92]
I get an error when I try to load in the data by the example.  Anyone else had this issue?

Error in get_acs(state = "MI", county = "Kent", geography = "tract", variables = "B19013_001", : A Census API key is required. Obtain one at http://api.census.gov/data/key_signup.html, and then supply the key to the `census_api_key` function to use it throughout your tidycensus session.

**Comment by dykesb** [comment]
Duplicate of #93
