### ISSUE TITLE
application 9 reading data

### ISSUE THREAD

**Issue by dirksem** [STA518-Spring20/discussion#93]
I get an error when I try to load in the data by the example. Anyone else had this issue?

Error in get_acs(state = "MI", county = "Kent", geography = "tract", variables = "B19013_001", : A Census API key is required. Obtain one at http://api.census.gov/data/key_signup.html, and then supply the key to the census_api_key function to use it throughout your tidycensus session.

**Comment by dykesb** [comment]
Did you obtain an API key?

**Comment by dirksem** [comment]
It wants an organization name and email.  Should we use or personal name or GVSU for our organization?

**Comment by dykesb** [comment]
I'm sure that should be fine.

**Comment by dirksem** [comment]
After I got a key and applied it to the "census_api_key" function WITHOUT the "install = TRUE" and "overwrite = TRUE", then it properly loaded in data. Thanks!

**Comment by chycinsa** [comment]
I activated my key but it is still telling me I don't have a proper key to access the data.

**Comment by dykesb** [comment]
Did you follow what dirksem did?

**Comment by sharnjitvirk** [comment]
I had a similar problem, I fixed it by putting the key in quotations.

**Comment by dykesb** [comment]
@sharnjitvirk Can you explain why you think the quotations are needed?

**Comment by sharnjitvirk** [comment]
Not sure, i think its because its a combination of numbers and characters which would require quotations and also because its not an object.

**Comment by dykesb** [comment]
@sharnjitvirk correct! The `key` argument is looking for a character string. In R, we specify this in quotes. From the `census_api_key` help documentation (**emphasis** added):

> key: The API key provided to you from the Census formated **in quotes**. A key can be acquired at http://api.census.gov/data/key_signup.html
