### ISSUE TITLE
application 9 inset using patchwork

### ISSUE THREAD

**Issue by sharnjitvirk** [STA518-Spring20/discussion#97]
I am having trouble figuring out how to inset the kent county map without using anything from cowplot. The closest equivalent I can find is plot_layout() but I don't understand how the argument you are supposed to pass in work.

**Comment by Rand3rino** [comment]
I used the ```/``` and ```|``` to get something similar to an inset.
I had a michigan map, a kent county map, and a blank visual. My plot was split into 4 quadrants and had the empty map in the top left, kent county in the bottom left, and my michigan map as the right half of the plot window.

**Comment by NickDuley** [comment]
https://www.r-bloggers.com/inset-maps-with-ggplot2/

I found this page to be useful for a basic inset map

**Comment by Rand3rino** [comment]
Isn't draw_plot() part of the cowplot package? I don't think we can use this.

**Comment by NickDuley** [comment]
My bad. You're right

**Comment by dykesb** [comment]
Here are some more examples from the documentation: 

https://patchwork.data-imaginist.com/articles/guides/assembly.html
https://patchwork.data-imaginist.com/articles/guides/layout.html
