### ISSUE TITLE
Activity 3.3 jasmines package 

### ISSUE THREAD

**Issue by schmimol** [STA518-Spring20/discussion#99]
I can't get the jasmines package to install. It's saying "package ‘jasmines’ is not available (for R version 4.0.0)"

**Comment by dykesb** [comment]
**jasmines** isn't on CRAN (i.e., install via `install.packages()`) so you'll need to install from GitHub. These lines should be ran in your Console:

```
Install.packages("remotes")
remotes::install_github("thomasp85/ambient")
remotes::install_github("djnavarro/jasmines")
```

Source: https://github.com/djnavarro/jasmines

**Comment by schmimol** [comment]
That did it, thanks!
